### PR TITLE
[18.0][MIG] hr_holidays_public: Migration to 18.0

### PR DESCRIPTION
**Pull request by xaviedoanhduy**
### Change on version 18.0

- `number_of_hours_display` fields has been removed in `https://github.com/odoo/odoo/pull/156117
`
### On the occasion

- I also removed some redundant code in tests (no need to call the denpends function)

### OCA - port

-  [17.0][FW] hr_holidays_public: port from 14.0: `https://github.com/OCA/hr-holidays/pull/144`

### CODE REVIEW

**Review by henrybackman — APPROVED** [review]

**Comment by simahawk** [comment]
to be moved to OCA

**Comment by simahawk** [comment]
Also, consider implementing https://github.com/OCA/hr-holidays/pull/111

**Comment by xaviedoanhduy** [comment]
replaced by: `https://github.com/OCA/hr-holidays/pull/147`

**Comment by xaviedoanhduy** [comment]
Supersedes: https://github.com/OCA/hr-holidays/pull/147

**Pull request closed without merging**
